"""Build lyrics/lyrics.src.js: the lyric sheet in this recording's structure,
with approximate line times taken from the Whisper transcript.

The supplied sheet had two choruses and line times ~3 s apart; this recording
sings the lines ~1.8 s apart and has four choruses (two after the instrumental
break). The words come from the sheet (Whisper mishears some of them); only the
timing comes from Whisper, by matching the sheet's words to Whisper's words.
The supplied sheet read "Lieb nicht wie ich wär" / "Lieb nicht weil du musst"; this
recording sings "Lieb mich" there (Whisper hears it and it aligns better in all eight
places, see align.py VARIANTS), so the sheet below follows the recording.

Run:  uv run python sheet.py   (after transcribe.py)
"""
import common
import difflib
import json
import re

VERSE1 = """Ich halt den Atem an
Sie ist schön wunderschön
Ich halt den Atem an
Wird sie bleiben oder gehen
Ich verzehr mich
Wart schon so lange hier
Wie ein Panther auf der Fährte seines Beutetieres
Ja ich verzehr mich
Und ich will doch nur lieben
Und noch in dieser Nacht
An ihrer Seite liegen
Sanft singt der Rabe im Wind"""

VERSE2 = """Ich halt den Atem an
Du bist schön so wunderschön
Ich halt den Atem an
Du bezahlst und willst schon gehen
Ja doch ich folg Dir
Ich folg auf Schritt und Tritt
Keine Ahnung wo du hinwillst
Doch da komm ich mit
Ja und ich folg Dir
Ich will doch nur lieben
Und noch in dieser Nacht
An deiner Seite liegen
Sanft singt der Rabe im Wind"""

CHORUS = """Lieb mich wie ich bin
Lieb mich wie ich wär
Lieb mich wie du willst
Und noch viel mehr
Lieb mich weil du kannst
Lieb mich weil du musst
Von heut an bis zum Schluss
Lieb mich wenn ich wein
Lieb mich wenn ich lach
Lieb mich wie du willst
Bei Tag und Nacht
Lieb mich einfach so
Lieb doch was ich bin
Nur so macht Liebe sinn"""

STRUCTURE = [VERSE1, CHORUS, VERSE2, CHORUS, CHORUS, CHORUS]


def key(w):
    return re.sub(r"[^a-zäöüß]", "", w.lower())


def align_words(a, b):
    """Global in-order alignment (edit distance) of two word lists; returns the
    (i, j) pairs of equal or near-equal words. Unlike difflib it cannot pin a
    repeated chorus to the wrong repeat."""
    sim = lambda x, y: difflib.SequenceMatcher(a=x, b=y).ratio()
    n, m = len(a), len(b)
    INF = float("inf")
    D = [[INF] * (m + 1) for _ in range(n + 1)]
    D[0] = [float(j) for j in range(m + 1)]
    for i in range(1, n + 1):
        D[i][0] = float(i)
        for j in range(1, m + 1):
            c = 1.0 - sim(a[i - 1], b[j - 1])
            D[i][j] = min(D[i - 1][j - 1] + 2 * c, D[i - 1][j] + 1, D[i][j - 1] + 1)
    pairs, i, j = [], n, m
    while i and j:
        c = 1.0 - sim(a[i - 1], b[j - 1])
        if D[i][j] == D[i - 1][j - 1] + 2 * c:
            if c < 0.5:
                pairs.append((i - 1, j - 1))
            i, j = i - 1, j - 1
        elif D[i][j] == D[i - 1][j] + 1:
            i -= 1
        else:
            j -= 1
    return pairs[::-1]


def main():
    lines = [l for block in STRUCTURE for l in block.splitlines()]
    sheet = [(li, w) for li, l in enumerate(lines) for w in l.split()]
    wh = [w for s in json.loads((common.WORK / "whisper.json").read_text()) for w in s["words"]]
    t_of = {}  # sheet word index -> (start, end)
    for a, b in align_words([key(w) for _, w in sheet], [key(w["w"]) for w in wh]):
        t_of[a] = (wh[b]["start"], wh[b]["end"])
    out = []
    for li, text in enumerate(lines):
        idx = [k for k, (l, _) in enumerate(sheet) if l == li]
        hit = [t_of[k] for k in idx if k in t_of]
        if not hit:  # filled in from the neighbours below
            out.append([None, None, text, f"0/{len(idx)}"])
            continue
        out.append([round(min(h[0] for h in hit), 2), round(max(h[1] for h in hit), 2), text,
                    f"{len(hit)}/{len(idx)}"])
    for i, o in enumerate(out):
        if o[0] is None:
            o[0] = round(out[i - 1][1] + 0.05, 2)
            o[1] = round(next(x[0] for x in out[i + 1:] if x[0] is not None) - 0.05, 2)
    # a line with only some words matched can be short: extend it to the neighbours
    for i, o in enumerate(out):
        if o[3].split("/")[0] != o[3].split("/")[1]:
            lo = out[i - 1][1] if i else o[0] - 1.0
            hi = out[i + 1][0] if i + 1 < len(out) else o[1] + 1.0
            o[0], o[1] = round(min(o[0], lo + 0.05), 2), round(max(o[1], hi - 0.05), 2)
    body = ",\n".join("  " + json.dumps(o[:3], ensure_ascii=False) for o in out)
    common.LYRICS_SRC.write_text(
        "// Line-level lyrics with approximate timings: (start s, end s, text) per line.\n"
        "// Generated by analysis/sheet.py: words from the supplied lyric sheet in this\n"
        "// recording's structure (four choruses), times from the Whisper transcript.\n"
        f"export const LY = [\n{body}\n];\n", encoding="utf-8")
    for o in out:
        print(f"{o[0]:7.2f} {o[1]:7.2f}  {o[3]:>5}  {o[2]}")
    print(len(out), "lines ->", common.LYRICS_SRC)


if __name__ == "__main__":
    main()
